"""all models

Revision ID: 7bb77bd7d6c4
Revises: 9ec4b3cbb1cb
Create Date: 2021-06-29 20:46:55.156697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bb77bd7d6c4'
down_revision = '9ec4b3cbb1cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cabins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('beds', sa.Integer(), nullable=False),
    sa.Column('total_capacity', sa.Integer(), nullable=False),
    sa.Column('img_url', sa.String(), nullable=True),
    sa.Column('ranch_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ranch_id'], ['ranches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ranch_id', sa.Integer(), nullable=True),
    sa.Column('guest_id', sa.Integer(), nullable=True),
    sa.Column('cabin_id', sa.Integer(), nullable=True),
    sa.Column('interests', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['cabin_id'], ['cabins.id'], ),
    sa.ForeignKeyConstraint(['guest_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ranch_id'], ['ranches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guest_id', sa.Integer(), nullable=True),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('additional_charges', sa.Integer(), nullable=True),
    sa.Column('deposit', sa.Boolean(), nullable=False),
    sa.Column('rollover_payment', sa.Boolean(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('amount_paid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['guest_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoices')
    op.drop_table('bookings')
    op.drop_table('cabins')
    # ### end Alembic commands ###
